language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
before_script:
  - npm prune
script:
  - npm run test
after_success:
  - npm run coveralls || true
  - node scripts/prepare-for-npm
  - npm publish ./npm
  - npm run github-release || true
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
