language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
script:
  - npm run test
  - node scripts/prepare-for-npm
deploy:
  on:
    branch: master
    tags: true
  provider: script
  skip_cleanup: true
  script: sh scripts/deploy.sh $TRAVIS_TAG
